### ISSUE TITLE
Repair Function

### ISSUE THREAD

**Issue by Applejakerie** [Applejakerie/AJs-Tanoa-Liberation-0.924#1]
>Repair trucks or containers really don't want to work anymore. 
>Nothing repairs aside for the FA18 mod.
- It's not the new trucks and it's certainly not the old containers. 
- In fact I don't think it's got anything to do with Apex as pre-Apex vehicles are broke too.

![capture](https://cloud.githubusercontent.com/assets/20494241/16897904/9e294204-4bb9-11e6-9e80-a0d8fc00a54b.PNG)

Anyone see a mistake?

**Comment by Applejakerie** [comment]
So I've found that vehicles will repair, once damaged enough. I'd like tonnes of feedback on this matter, how it's working for your servers and how well it works, or rather what requirements you seem to need to meet to make it work. Thanks guys. **Just comment them here.**

**Comment by Applejakerie** [comment]
Okay so the damage function is outdated, I just need to find a way around it.

**Comment by wingwalker73** [comment]
My team started playing this yesterday. I can say that repair is working on all fronts: Huron repair container repairs Hurons and the HEMTT Repair is working on other vehicles. I will say this, though: We are using RHS and we had some issues with Altis Liberation after we introduced RHS. It has its own damage model and they seemed to conflict. But, we just updated RHS to it's latest release prior to starting this Liberation and repair is working perfectly. Dunno if that helps you or just confuses you more. :-/

**Comment by Applejakerie** [comment]
Thanks for the feedback! I'm going to start looking into this again. In my own experience though, it worked perfectly on Altis and even Tanoa and then after an update somewhere, the entire function seemed to be different and looking for incorrect values (like a higher damage amount).

I'm not sure in how RHS is different but the usual function just checked a vehicle for damage, if it was above 0.01%, it would initiate the repair, so even a popped tyre was enough for the process to begin. 

It's strange, seems to be different on different servers too so I need to check versioning.

**Comment by wingwalker73** [comment]
I remember that on Altis. We did figure out that it wouldn't repair unless it was a significant amount of damage. But on the Tanoa version, it works no matter what. If you want to stop by our server, let me know and we can look around.

**Comment by Applejakerie** [comment]
Sounds perfect, if you could drop me an address for your server and a link to your mission.pbo so I can have one last check for peace of mind, I'd much appreciate it!

**Comment by wingwalker73** [comment]
I'll send it privately via the BIS forums. The mission file is your latest here:
https://github.com/Applejakerie/AJs-Tanoa-Liberation-0.924

**Comment by Applejakerie** [comment]
Perfect and just checking, thanks!
