### ISSUE TITLE
Build menu not working

### ISSUE THREAD

**Issue by Darkz** [Applejakerie/AJs-Tanoa-Liberation-0.924#2]
Even if i have the resources, The build menu does not appear.

Is this a known issue? or its a problem of my server?

**Comment by Applejakerie** [comment]
It's definitely not a known issue, no.
Could you give me some more information?

The requirements to see the "BUILD" option in the scroll menu are just that you are standing within 125m of an FOB. Not Chimera, though. Chimera has no "BUILD" option.

Even if you don't have the resources you can still see the full menu.

**Comment by Sirys** [comment]
Hi, I'm working on the same dedicated server as Darkz and noticed that if the option "FirstFob" is enabled  it will spawn an overlapping Alpha FOB on top of the chimera base so you can't build or spawn in it.

Also, the commander can't use the limited zeus interface when playing in a dedicated server, when using the map locally it does, even gives you artillery support o.o.

And tanks for porting this amazing game mode to tanoa!

**Comment by Applejakerie** [comment]
Ah okay, I think that's my bad. 

Will need to look into how the FOB's locations are picked and then just simply re-adjust them to more sensible possible places. Will try and do that today alongside the repair issue, which by the way does work but the vehicle needs to be heavily damaged, that's to the damage function being outdated (and so the code for it). Again, I'm not a scripter but I'll work on it to the best of my capabilities. 

For now, I'd suggest disabling the first FOB option and just carrying the container from Chimera to somewhere; there's a small nook in the forest nearby, before the radio tower that has some pre-built stuff, gates, bunkers, tower and helipad if I remember correctly. You'll have to capture the radio tower to free up the "BUILD" menu tho but if you run downhill enough, you can build there and run back up. ;)

The Commander role for some reason doesn't always display the Zeus and artillery interface no, I don't think it's to do with the server type but just the random Arma logic we all have to work around. I've found that dying, kicks it in if it hasn't already. This is the same for many servers using Zeus.
